market_prj/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('users/read/', adminapp.TravelUsersListView.as_view(), name='users'),
    path('users/create/', adminapp.travel_user_create, name='user_create'),
    path('users/update/<int:pk>/', adminapp.travel_user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.travel_user_delete, name='user_delete'),

    path('countries/read/', adminapp.countries, name='countries'),
    path('countries/create/', adminapp.CountryCreateView.as_view(),
         name='country_create'),
    path('countries/update/<pk>/', adminapp.CountryUpdateView.as_view(),
         name='country_update'),
    path('countries/delete/<pk>/', adminapp.CountryDeleteView.as_view(),
         name='country_delete'),

    path('accommodation/read/countries/<pk>/', adminapp.accommodations,
         name='accommodations'),
    path('accommodation/create/countries/<pk>/',
         adminapp.accommodation_create, name='accommodation_create'),
    path('accommodation/update/<pk>/', adminapp.accommodation_update,
         name='accommodation_update'),
    path('accommodation/read/<pk>/',
         adminapp.AccommodationDetailView.as_view(),
         name='accommodation_read'),
    path('accommodation/delete/<pk>/',
         adminapp.accommodation_delete, name='accommodation_delete'),
]

market_prj/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

market_prj/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<pk>/<int:nights>/', basketapp.basket_edit, name='edit'),
]

market_prj/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.accommodations, name='index'),
    path('accommodation_details/<pk>/', mainapp.accommodation, name='accommodation'),
]

market_prj/market_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

market_prj/mainapp/models.py
import uuid
# Create your models here.
# from django.conf import settings

from django.db import models
import authapp
class PartsOfWorld(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name
class ListOfCountries(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    partsofworld = models.ForeignKey(PartsOfWorld, on_delete=models.CASCADE,blank=True,default=None,null=True)
    def __str__(self):
        return self.name

class Regions(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name
    @staticmethod
    def get_regions_of_countryes(lst_countryes):
        return Regions.objects.filter(country_id__in=lst_countryes)
class Accommodation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    region = models.ForeignKey(Regions, on_delete=models.CASCADE, related_name='Regionid')
    name = models.CharField(verbose_name='название проживания',
                                           max_length=128, unique=True)
    image = models.ImageField(upload_to='accommodation_img', blank=True)
    short_desc = models.TextField(verbose_name='краткое описание продукта',
                                  max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта',
                                   blank=True)
    availability = models.PositiveIntegerField(
				verbose_name='количество свободных номеров')
    price = models.DecimalField(
        verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    room_desc = models.TextField(verbose_name='краткое описание комнаты',
                                 max_length=60, blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    @staticmethod
    def get_items():
        reslt = Accommodation.objects.filter(is_active=True).order_by('region_id__country_id','regions','name')
        return reslt

    @staticmethod
    def get_country_items(country_id, join_type):
        list_of_accommodations2 = Accommodation.objects.select_related('region')
        if join_type=='country':
            list_of_accommodations2 = list_of_accommodations2.select_related('country')
        if isinstance(country_id,list):
            # print('country_id(list)=', country_id)
            list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id__in=country_id)

        elif country_id:
            list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id=uuid.UUID(country_id))

        list_of_accommodations2 = list_of_accommodations2.order_by('region_id__country_id','region_id','name')
        return list_of_accommodations2

    @staticmethod
    def get_parametrs_items(param_id,param_type, join_type):
        list_of_accommodations2 = Accommodation.objects.select_related('region')
        if join_type == 'country':
            list_of_accommodations2 = list_of_accommodations2.select_related('country')
        if isinstance(param_id, list):
            print('param_id(list)=', param_id)
            if param_type=='country':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id__in=param_id)
            elif param_type=='region':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__in=param_id)
        elif param_id:
            if param_type=='country':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id=uuid.UUID(param_id))
            elif param_type == 'region':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id=uuid.UUID(param_id))
            print('param_id()=', uuid.UUID(param_id))
        list_of_accommodations2 = list_of_accommodations2.order_by('region_id__country_id', 'region_id', 'name')
        return list_of_accommodations2

    def __str__(self):
        return f'{self.name} ({self.country.name})'
class Apartmen(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название типа номеров',
                                           max_length=128, unique=True)
    image = models.ImageField(upload_to='apartmen_img', blank=True,default=None)
    short_desc = models.TextField(verbose_name='краткое описание типа номеров',
                                  max_length=60, blank=True,default=None)
    description = models.TextField(verbose_name='описание типа номеров',
                                   blank=True,default=None)
    availability = models.PositiveIntegerField(
				verbose_name='количество свободных номеров',default=None)
    price = models.DecimalField(
        verbose_name='цена % об базового тарифа', max_digits=8, decimal_places=2, default=0)

    @staticmethod
    def get_accommodation_items(accommodation):
        return Apartmen.objects.filter(accommodation=accommodation)
    def __str__(self):
        return f'{self.name} ({self.accommodation.name})'

market_prj/mainapp/forms.py
from django import forms
from mainapp.models import Apartmen


class ApartmenForm(forms.ModelForm):
    model = Apartmen
    is_choise = forms.BooleanField(label='Выбрано', required=False)
    exclude = ()

    def __init__(self, *args, **kwargs):
        super(Apartmen, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

market_prj/mainapp/views.py
from django.shortcuts import render
from django.contrib import auth
from authapp.models import TravelUser,TravelUserProfile,UserCaseProfile
import authapp
from django.shortcuts import get_object_or_404
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic.detail import DetailView
from mainapp.models import Apartmen
from basketapp.models import Basket
import uuid
def main(request):
    return render(request, 'mainapp/index.html')

# Create your views here.

from .models import Accommodation, Regions, ListOfCountries
def accommodations(request):
    title = 'размещение'
    format = 'icons'
    typeparam = None
    cntcase = None
    curent_user = auth.get_user(request)
    profile_curr_user = TravelUserProfile.objects.filter(user=curent_user.id)
    # print(list(profile_curr_user.values('accomm_format')),curent_user.id)
    curr_profile =  profile_curr_user.values('accomm_format')
    if curr_profile:
        format = curr_profile[0]['accomm_format']
    if request.method == 'POST':
        print(request.POST)
        if request.POST.get('btn_format'):
            # print('1')
            # format = request.POST.get('format')
            if format == 'table':
                format = 'icons'
            elif format == 'icons':
                format = 'table'
        if request.POST.get('btnс') and curent_user:
            btnc_id = request.POST.get('btnс')
            typeparam = 'country'
            UserCaseProfile.update_user_countryes(userid=curent_user.id, countryid=btnc_id)
        if request.POST.get('btnr') and curent_user:
            btnr_id = request.POST.get('btnr')
            typeparam = 'region'
            UserCaseProfile.update_user_parametrs(userid=curent_user.id,parametrid= btnr_id,param_type='region')
        if request.POST.get('btn_country_clear') and curent_user:
            print('free country')
            typeparam = 'country'
            UserCaseProfile.update_user_countryes(userid=curent_user.id, countryid='free')
        if (request.POST.get('btnс') or request.POST.get('btn_countryes')) and curent_user:
            print('btn2')
            typeparam = 'country'
            cntcase = list(UserCaseProfile.objects.filter(user_id=curent_user.id,context='country').values_list('param_id',flat=True))
        if request.POST.get('btn_region_clear') and curent_user:
            print('free region')
            typeparam = 'region'
            UserCaseProfile.update_user_parametrs(userid=curent_user.id, parametrid='free',param_type='region')
            # get_regions_of_countryes
        if request.POST.get('btnr_of_countryes') and curent_user:
            typeparam = 'region'
            countryes_case1 = list(UserCaseProfile.objects.filter(user_id=curent_user.id, context='country').values_list('param_id',flat=True))
            print('countryes_case1=',countryes_case1)
            cntcase = list(Regions.get_regions_of_countryes(countryes_case1).values_list('id',flat=True))
            UserCaseProfile.update_user_parametrs(userid=curent_user.id, parametrid=cntcase, param_type='region')
        if (request.POST.get('btnr') or request.POST.get('btn_regions')) and curent_user:
            print('btnr')
            typeparam = 'region'
            cntcase = list(UserCaseProfile.objects.filter(user_id=curent_user.id,context='region').values_list('param_id',flat=True))

        TravelUserProfile.objects.filter(user_id=curent_user.id).update(accomm_format=format)
        # print(btn_format)
    # list_of_accommodations = Accommodation.objects.filter(is_active=True)
    print('countryes_case=', cntcase)
    # list_of_accommodations = Accommodation.get_country_items(countryes_case,'country')
    list_of_accommodations = Accommodation.get_parametrs_items(param_id=cntcase, param_type=typeparam, join_type='country')
    # list_of_accommodations = Accommodation.get_country_items('00000000-0000-0000-0000-000000000003','country')
    list_of_country = ListOfCountries.objects.values('id','name')
    List_of_regions = Regions.objects.select_related('country').values('id','name','country_id','country_id__name')
    for elm in list_of_country:
        # print(elm['id'])
        if UserCaseProfile.objects.filter(user_id=curent_user.id, param_id=elm['id'], context='country'):
            elm['is_active'] = True
        else:
            elm['is_active'] = False
    for elm in List_of_regions:
        # print(elm['id'])
        if UserCaseProfile.objects.filter(user_id=curent_user.id, param_id=elm['id'], context='region'):
            elm['is_active'] = True
        else:
            elm['is_active'] = False
    # for a in list_of_accommodations:
    #     print('accomm=',a.name,a.region,a.region.country)
    pagename = 'accommodations'
    content = {
        'title': title,
        'pagename': pagename,
        'list_of_accommodations': list_of_accommodations,
        'list_of_country': list_of_country,
        'list_of_regions': List_of_regions,
        'format': format,
    }

    return render(request, 'mainapp/accommodations.html', content)

from django.shortcuts import get_object_or_404
from .models import ListOfCountries

def accommodation(request, pk):
    title = 'продукты'
    list_apartmen = Apartmen.get_accommodation_items(pk)
    accommodation = get_object_or_404(Accommodation, pk=pk)
    if request.method == 'POST':
        if request.POST.get('btn_accom_add'):
            val = request.POST.getlist('radio_app')
            if val and request.user:
                for elm in list_apartmen:
                    if str(elm.id) in list(val):
                        # print(request.user.id)
                        if request.user.id:
                            basket = Basket.objects.filter(user=request.user,accommodation_id=pk,apartmen_id=elm.id).first()
                        else:
                            basket = None
                        if not basket and request.user.id:
                            basket = Basket(user=request.user, accommodation=accommodation,
                                            country_id=accommodation.region.country_id,apartmen_id=elm.id)
                        if request.user.id:
                            basket.nights += 1
                            basket.save()

    content = {
        'title': title,
        'accommodation': get_object_or_404(Accommodation, pk=pk),
        'list_apartmen': list_apartmen,
        'is_apartmen': len(list_apartmen)
    }
    # print('request=',request)
    return render(request, 'mainapp/accommodation_details.html', content)

class ApartmenList(ListView):
    model = Apartmen
    def get_queryset(self):
        print('self.request=', self.request)
        return Apartmen.objects.filter( accommodation_id=self.request.accommodation_id)

market_prj/mainapp/templates/mainapp/includes/apartmens_list.html
<table class="table apartmens_list">
        <thead>
        <tr>
            <th>Имя</th>
            <th>Наценка %</th>
            <th>Выбрать</th>
        </tr>
        </thead>
        <tbody>
        <fieldset>
        {% for item in list_apartmen %}
            <tr>
<!--                <td class="td1 apartmens_list">{{ item.is_choise }}</td>-->
                <td>{{ item.name|title }}</td>
                <td>{{ item.price }}</td>
                <td>
                    <div>
                    <input type="checkbox" id= {{ item.id }} name="radio_app" value={{ item.id }} />
                    </div>
                </td>
            </tr>
        {% endfor %}
        </fieldset>
        </tbody>
    </table>

market_prj/mainapp/templates/mainapp/includes/inc_footer.html
<div class="page-footer font-small unique-color-dark">
            <div class="container">
                <div class="row py-4 d-flex align-items-center">
                    <div class="col-md-6 col-lg-5
                    text-center text-md-left mb-4 mb-md-0">
                        <h6 class="mb-0 text-center">
                            И весь мир у вас на ладони</h6>
                    </div>
                    <div class="col-md-6 col-lg-7 text-center text-md-right">

                        <!-- Facebook -->
                        <a class="fb-ic">
                            <i class="fab fa-facebook-f white-text mr-4"> </i>
                        </a>
                        <!-- Twitter -->
                        <a class="tw-ic">
                            <i class="fab fa-twitter white-text mr-4"> </i>
                        </a>
                        <!-- Google +-->
                        <a class="gplus-ic">
                            <i class="fab fa-google-plus-g
                            white-text mr-4"> </i>
                        </a>
                        <!--Linkedin -->
                        <a class="li-ic">
                            <i class="fab fa-linkedin-in white-text mr-4"> </i>
                        </a>
                        <!--Instagram-->
                        <a class="ins-ic">
                            <i class="fab fa-instagram white-text"> </i>
                        </a>

                    </div>
                </div>
            </div>
            <div class="container text-center text-md-left mt-5">
                <div class="row mt-3">
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <h6 class="text-uppercase font-weight-bold">О нас</h6>
                        <hr class="deep-purple accent-2 mb-4 mt-0
                         d-inline-block mx-auto" style="width: 60px;">
                        <p>Thank you for patience and understanding.</p>

                    </div>
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase font-weight-bold">Страны</h6>
                        <hr class="deep-black accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                    </div>
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <h6 class="text-uppercase font-weight-bold">
                            Полезные ссылки</h6>
                        <hr class="deep-purple accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                        <p>
                            <a href="#!">...</a>
                        </p>
                    </div>
                    <div class="col-md-4 col-lg-3
                    col-xl-3 mx-auto mb-md-0 mb-4">
                        <hr class="deep-purple accent-2 mb-4 mt-0
                        d-inline-block mx-auto" style="width: 60px;">
                        <p>
                            <i class="fas fa-home mr-3"></i>
                            Moscow, Russia</p>
                        <p>
                            <i class="fas fa-envelope mr-3"></i>
                            user@mail.ru</p>
                        <p>
                            <i class="fas fa-phone mr-3"></i>
                            + 01 000 567 88</p>
                        <p>
                            <i class="fas fa-print mr-3"></i>
                            + 01 000 567 89</p>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center py-3">&copy; 2020 Copyright:
                <a href="#">thereisnomercy.com</a>
            </div>
        </div>

market_prj/mainapp/templates/mainapp/includes/inc_menu.html
<div class="">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'main' %}">TravelMarket</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item"><a class="nav-link"
                                    href="{% url 'acc:index' %}">
                забронировать размещение</a></li>
            {% if pagename == "accommodations" and user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                       href="" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                    Фильтр стран
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'acc:index' %}">
                            Все
                        </a>
                        <form method="post">
                        {% csrf_token %}
                            <button type="submit" name="btn_countryes" id="btn_countryes" value="btn_countryes">
                                Применить
                            </button>
                            <button type="submit" name="btn_country_clear" id="btn_country_clear" value="btn_country_clear">
                                Сбросить
                            </button>

                            {% for countr in list_of_country %}
                            <div>
                                <button type="submit" name="btnс" id="btnс_{{ countr.id }}" value="{{ countr.id }}">
                                    {% if countr.is_active %}
                                        [x] {{ countr.name|title }}
                                    {% else %}
                                        [ ] {{ countr.name|title }}
                                    {% endif %}

                                </button>

                            </div>

                            {% endfor %}
                        </form>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"
                       href="" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                    Фильтр регионов
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'acc:index' %}">
                            Все
                        </a>
                        <form method="post">
                        {% csrf_token %}
                            <button type="submit" name="btn_regions" id=btn_regions" value="btn_regions">
                                Применить
                            </button>
                            <button type="submit" name="btn_region_clear" id="btn_region_clear" value="btn_region_clear">
                                Сбросить
                            </button>
                            <button type="submit" name="btnr_of_countryes" id="btnr_of_countryes" value="btnr_of_countryes">
                                + Регионы стран
                            </button>

                            {% for countr in list_of_regions %}
                            <div>
                                <button type="submit" name="btnr" id="btnс_{{ countr.id }}" value="{{ countr.id }}">
                                    {% if countr.is_active %}
                                        [x] {{ countr.name|title }}/{{ countr.country_id__name|title }}
                                    {% else %}
                                        [ ] {{ countr.name|title }}/{{ countr.country_id__name|title }}
                                    {% endif %}

                                </button>

                            </div>

                            {% endfor %}
                        </form>
                </div>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                {% if user.is_authenticated %}

                    <a class="nav-link dropdown-toggle"
                       href="" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        {{ user|default:'пользователь' }}
                    </a>
                    <a class="dropdown-item" href="{% url 'basket:view' %}">
                        корзина
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'auth:edit' %}">профиль</a>

                        {% if user.is_superuser %}
                            <div class="dropdown-divider"></div>

                        {% endif %}
                    </div>

                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'auth:logout' %}">выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'auth:login' %}">войти</a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'admin:users' %}">админка</a>
                {% endif %}

            </li>


        </ul>
        <form class="form-inline my-2 my-lg-0" >
            <input class="form-control mr-sm-1 " action="{% url 'acc:index' %}"
                   type="search" placeholder="Поиск на сайте" aria-label="Search"
            name="search">
            <button class="btn btn-outline-danger my-2 my-sm-0 disabled"
                    type="submit">Поиск</button>
        </form>

    </div>
</nav>
</div>