market_prj/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

market_prj/basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<pk>/<int:nights>/', basketapp.basket_edit, name='edit'),
]

market_prj/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.accommodations, name='index'),
    path('accommodation_details/<pk>/', mainapp.accommodation, name='accommodation'),
]

market_prj/market_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', mainapp.main, name='main'),
    path('list_of_accommodations/', include('mainapp.urls', namespace='acc')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

market_prj/mainapp/models.py
import uuid
# Create your models here.
# from django.conf import settings

from django.db import models
import authapp
class PartsOfWorld(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name
class ListOfCountries(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    partsofworld = models.ForeignKey(PartsOfWorld, on_delete=models.CASCADE,blank=True,default=None,null=True)
    def __str__(self):
        return self.name

class Regions(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name
    @staticmethod
    def get_regions_of_countryes(lst_countryes):
        return Regions.objects.filter(country_id__in=lst_countryes)
class Accommodation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    country = models.ForeignKey(ListOfCountries, on_delete=models.CASCADE)
    region = models.ForeignKey(Regions, on_delete=models.CASCADE, related_name='Regionid')
    name = models.CharField(verbose_name='название проживания',
                                           max_length=128, unique=True)
    image = models.ImageField(upload_to='accommodation_img', blank=True)
    short_desc = models.TextField(verbose_name='краткое описание продукта',
                                  max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта',
                                   blank=True)
    availability = models.PositiveIntegerField(
				verbose_name='количество свободных номеров')
    price = models.DecimalField(
        verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    room_desc = models.TextField(verbose_name='краткое описание комнаты',
                                 max_length=60, blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    @staticmethod
    def get_items():
        reslt = Accommodation.objects.filter(is_active=True).order_by('region_id__country_id','regions','name')
        return reslt

    @staticmethod
    def get_country_items(country_id, join_type):
        list_of_accommodations2 = Accommodation.objects.select_related('region')
        if join_type=='country':
            list_of_accommodations2 = list_of_accommodations2.select_related('country')
        if isinstance(country_id,list):
            # print('country_id(list)=', country_id)
            list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id__in=country_id)

        elif country_id:
            list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id=uuid.UUID(country_id))

        list_of_accommodations2 = list_of_accommodations2.order_by('region_id__country_id','region_id','name')
        return list_of_accommodations2

    @staticmethod
    def get_parametrs_items(param_id,param_type, join_type):
        list_of_accommodations2 = Accommodation.objects.select_related('region')
        if join_type == 'country':
            list_of_accommodations2 = list_of_accommodations2.select_related('country')
        if isinstance(param_id, list):
            print('param_id(list)=', param_id)
            if param_type=='country':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id__in=param_id)
            elif param_type=='region':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__in=param_id)
        elif param_id:
            if param_type=='country':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id__country_id=uuid.UUID(param_id))
            elif param_type == 'region':
                list_of_accommodations2 = list_of_accommodations2.filter(region_id=uuid.UUID(param_id))
            print('param_id()=', uuid.UUID(param_id))
        list_of_accommodations2 = list_of_accommodations2.order_by('region_id__country_id', 'region_id', 'name')
        return list_of_accommodations2

    def __str__(self):
        return f'{self.name} ({self.country.name})'
class Apartmen(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    accommodation = models.ForeignKey(Accommodation, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название типа номеров',
                                           max_length=128, unique=True)
    image = models.ImageField(upload_to='apartmen_img', blank=True,default=None)
    short_desc = models.TextField(verbose_name='краткое описание типа номеров',
                                  max_length=60, blank=True,default=None)
    description = models.TextField(verbose_name='описание типа номеров',
                                   blank=True,default=None)
    availability = models.PositiveIntegerField(
				verbose_name='количество свободных номеров',default=None)
    price = models.DecimalField(
        verbose_name='цена % об базового тарифа', max_digits=8, decimal_places=2, default=0)

    @staticmethod
    def get_accommodation_items(accommodation):
        return Apartmen.objects.filter(accommodation=accommodation)
    def __str__(self):
        return f'{self.name} ({self.accommodation.name})'

market_prj/mainapp/forms.py
from django import forms
from mainapp.models import Apartmen


class ApartmenForm(forms.ModelForm):
    model = Apartmen
    is_choise = forms.BooleanField(label='Выбрано', required=False)
    exclude = ()

    def __init__(self, *args, **kwargs):
        super(Apartmen, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

market_prj/mainapp/views.py
from django.shortcuts import render
from django.contrib import auth
from authapp.models import TravelUser,TravelUserProfile,UserCaseProfile
import authapp
from django.shortcuts import get_object_or_404
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic.detail import DetailView
from mainapp.models import Apartmen
from basketapp.models import Basket
import uuid
def main(request):
    return render(request, 'mainapp/index.html')

# Create your views here.

from .models import Accommodation, Regions, ListOfCountries
def accommodations(request):
    title = 'размещение'
    format = 'icons'
    typeparam = None
    cntcase = None
    curent_user = auth.get_user(request)
    profile_curr_user = TravelUserProfile.objects.filter(user=curent_user.id)
    # print(list(profile_curr_user.values('accomm_format')),curent_user.id)
    curr_profile =  profile_curr_user.values('accomm_format')
    if curr_profile:
        format = curr_profile[0]['accomm_format']
    if request.method == 'POST':
        print(request.POST)
        if request.POST.get('btn_format'):
            # print('1')
            # format = request.POST.get('format')
            if format == 'table':
                format = 'icons'
            elif format == 'icons':
                format = 'table'
        if request.POST.get('btnс') and curent_user:
            btnc_id = request.POST.get('btnс')
            typeparam = 'country'
            UserCaseProfile.update_user_countryes(userid=curent_user.id, countryid=btnc_id)
        if request.POST.get('btnr') and curent_user:
            btnr_id = request.POST.get('btnr')
            typeparam = 'region'
            UserCaseProfile.update_user_parametrs(userid=curent_user.id,parametrid= btnr_id,param_type='region')
        if request.POST.get('btn_country_clear') and curent_user:
            print('free country')
            typeparam = 'country'
            UserCaseProfile.update_user_countryes(userid=curent_user.id, countryid='free')
        if (request.POST.get('btnс') or request.POST.get('btn_countryes')) and curent_user:
            print('btn2')
            typeparam = 'country'
            cntcase = list(UserCaseProfile.objects.filter(user_id=curent_user.id,context='country').values_list('param_id',flat=True))
        if request.POST.get('btn_region_clear') and curent_user:
            print('free region')
            typeparam = 'region'
            UserCaseProfile.update_user_parametrs(userid=curent_user.id, parametrid='free',param_type='region')
            # get_regions_of_countryes
        if request.POST.get('btnr_of_countryes') and curent_user:
            typeparam = 'region'
            countryes_case1 = list(UserCaseProfile.objects.filter(user_id=curent_user.id, context='country').values_list('param_id',flat=True))
            print('countryes_case1=',countryes_case1)
            cntcase = list(Regions.get_regions_of_countryes(countryes_case1).values_list('id',flat=True))
            UserCaseProfile.update_user_parametrs(userid=curent_user.id, parametrid=cntcase, param_type='region')
        if (request.POST.get('btnr') or request.POST.get('btn_regions')) and curent_user:
            print('btnr')
            typeparam = 'region'
            cntcase = list(UserCaseProfile.objects.filter(user_id=curent_user.id,context='region').values_list('param_id',flat=True))

        TravelUserProfile.objects.filter(user_id=curent_user.id).update(accomm_format=format)
        # print(btn_format)
    # list_of_accommodations = Accommodation.objects.filter(is_active=True)
    print('countryes_case=', cntcase)
    # list_of_accommodations = Accommodation.get_country_items(countryes_case,'country')
    list_of_accommodations = Accommodation.get_parametrs_items(param_id=cntcase, param_type=typeparam, join_type='country')
    # list_of_accommodations = Accommodation.get_country_items('00000000-0000-0000-0000-000000000003','country')
    list_of_country = ListOfCountries.objects.values('id','name')
    List_of_regions = Regions.objects.select_related('country').values('id','name','country_id','country_id__name')
    for elm in list_of_country:
        # print(elm['id'])
        if UserCaseProfile.objects.filter(user_id=curent_user.id, param_id=elm['id'], context='country'):
            elm['is_active'] = True
        else:
            elm['is_active'] = False
    for elm in List_of_regions:
        # print(elm['id'])
        if UserCaseProfile.objects.filter(user_id=curent_user.id, param_id=elm['id'], context='region'):
            elm['is_active'] = True
        else:
            elm['is_active'] = False
    # for a in list_of_accommodations:
    #     print('accomm=',a.name,a.region,a.region.country)
    pagename = 'accommodations'
    content = {
        'title': title,
        'pagename': pagename,
        'list_of_accommodations': list_of_accommodations,
        'list_of_country': list_of_country,
        'list_of_regions': List_of_regions,
        'format': format,
    }

    return render(request, 'mainapp/accommodations.html', content)

from django.shortcuts import get_object_or_404
from .models import ListOfCountries

def accommodation(request, pk):
    title = 'продукты'
    list_apartmen = Apartmen.get_accommodation_items(pk)
    accommodation = get_object_or_404(Accommodation, pk=pk)
    if request.method == 'POST':
        if request.POST.get('btn_accom_add'):
            val = request.POST.getlist('radio_app')
            if val and request.user:
                for elm in list_apartmen:
                    if str(elm.id) in list(val):
                        # print(request.user.id)
                        if request.user.id:
                            basket = Basket.objects.filter(user=request.user,accommodation_id=pk,apartmen_id=elm.id).first()
                        else:
                            basket = None
                        if not basket and request.user.id:
                            basket = Basket(user=request.user, accommodation=accommodation,
                                            country_id=accommodation.region.country_id,apartmen_id=elm.id)
                        if request.user.id:
                            basket.nights += 1
                            basket.save()

    content = {
        'title': title,
        'accommodation': get_object_or_404(Accommodation, pk=pk),
        'list_apartmen': list_apartmen,
        'is_apartmen': len(list_apartmen)
    }
    # print('request=',request)
    return render(request, 'mainapp/accommodation_details.html', content)

class ApartmenList(ListView):
    model = Apartmen
    def get_queryset(self):
        print('self.request=', self.request)
        return Apartmen.objects.filter( accommodation_id=self.request.accommodation_id)

market_prj/mainapp/templates/mainapp/accommodation_details.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        <div class="media ">
            <img src="/media/{{ accommodation.image }}" 
                 class="img-fluid mt-2 col-lg-offset-4" 
						alt="Responsive image"
                 style="height: 300px">
            <div class="ml-1 container-fluid">
                <div class="align-content-lg-between text-center">
                    <h1 class="mt-3 ml-3">
				{{ accommodation.name|title }}</h1>
                    <br>
                    <p>месторасположение: 
				{{ accommodation.region|title }}</p>
                    <br>
                    <p>стоимость за сутки: {{ accommodation.price }}</p>
                    <br><br><br><br>
                </div>
                <form method="post">
                    {% csrf_token %}
                      {% if is_apartmen > 0 %}
                        {% include 'mainapp/includes/apartmens_list.html' %}
                        <button name="btn_accom_add" id="btn_accom_add" type="submit" value="ok">
                            Забронировать номера
                        </button>
                      {% endif %}
                    </form>

                <div class="float-right">
                    <button class="btn  btn-danger " >
                        <a style="color: white; text-decoration: none"
                           href="{% url 'basket:add' accommodation.pk %}">Забронировать базовые</a>
                    </button>

                </div>

            </div>

        </div>
        <div class="mt-3">
            <h3>Описание</h3>
            {{ accommodation.description|title }}
        </div>
    </div>

{% endblock %}

market_prj/mainapp/templates/mainapp/accommodations.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}


    <div class="container mt-3">
        <form method="post">
        {% csrf_token %}
            <button name="btn_format" id="btn_format" type="submit" value="{{format}}">
                {% if format == "table" %}
                    T
                {% endif %}
                {% if format == "icons" %}
                    L
                {% endif %}
            </button>

        </form>

        <div class="row centered">
            {% for offer in list_of_accommodations %}

                <div class="card  col-lg-4" style="width: 16rem; display: flex">
                    {% if format == "icons" %}
                        <img src="/media/{{ offer.image }}"
                            class="card-img-top filters__img" alt="...">
                    {% endif %}
                    <div class="card-body fa fa-align-justify">
                        <h5 class="card-title">{{ offer.name|title }}</h5>
                        <p class="card-text">{{ offer.region|title }}</p>
                        <p class="card-text">{{ offer.region.country|title }}</p>

                        <p class="card-text">{{ offer.price }} за 
								сутки.</p>
                        <a href="{% url 'acc:accommodation' offer.pk %}"
                           class="btn btn-danger">Подробнее</a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

market_prj/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
        <title>TravelMarket</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css"
              href="{% static 'css/style.css' %}">
        <link rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
    {% endblock %}
    {% block js %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>
    {% endblock %}


</head>
<body>
<div class="container">

    {% block menu %}
        {% include 'mainapp/includes/inc_menu.html' %}
    {% endblock %}

    {% block list %}

    {% endblock %}

    {% block content %}

    {% endblock %}

</div>
</body>
<footer>
    {% block footer %}
        {% include 'mainapp/includes/inc_footer.html' %}
    {% endblock %}
</footer>
</html>
</title>
</head>
<body>

</body>
</html>

market_prj/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="">
        <div id="carouselExampleFade" class="carousel slide
        carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/thai.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/beach.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/sands.jpg' %}"
                         class="d-block w-100" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade"
               role="button" data-slide="prev">
                <span class="carousel-control-prev-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next"
               href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon"
                      aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <div class="card nav-item">
            <div class="card-body">
                <h5 class="card-title">Отдых,
                    который Вы заслужили</h5>
                <p class="card-text">Лучшие и самые дешёвые
                    предложения на рынке от поставщиков</p>
                <a class="btn btn-danger"
                   href="{% url 'acc:index' %}">Смотреть размещение</a>
            </div>
        </div>
    </div>
{% endblock %}
</title>
</head>
<body>

</body>
</html>